# Generated by Django 3.2 on 2023-02-03 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230202_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Слаг содержит недопустимый символ.', regex='^[-a-zA-Z0-9_]+$')], verbose_name='Ник'),
        ),
    ]
